[Files]
plotPath = "Plots"
csvPath = "results_sheet.csv"
npzPath = "Npz"
provideXLSX = true
overwrite = false

[Video]
showVideoFrames = true
showEdgeDetection = false
playbackSpeed = "normal"

[Measurement]
roi = -1
rescaleFactor = 0.5
fromTime = -1
toTime = -1
pCRTAlgorithm = "first that works"
maxUncertaintyRatio = 1.0
initialGuesses = [1.0, -0.5, 0.0]

[General]
askConfirmation = true
writeLogFile = true
logLevel = "INFO"
enabledPlots = ["bgr_g", "lab_a"]
showPlots = true
simplerPlots = true
