[Files]
plotPath = "Plots"
csvPath = "results_sheet.csv"
npzPath = "Npz"
provideXLSX = true
overwrite = false

[Video]
rescaleFactor = 0.5
livePlot = false  # Leave as false if using Windows
displayVideo = true
playbackSpeed = "fast"

[Measurement]
roi = -1
channel = "g"
fromTime = 0
toTime = inf
sliceMethod = "from local max"
exclusionMethod = "first positive peak"
exclusionCriteria = inf
initialGuesses = [1.0, -0.5, 0.0]

[General]
askConfirmation = true
showPlots = true
writeLogFile = true
logLevel = "DEBUG"
