[Files]
plotPath = "Plots"
csvPath = "results_sheet.csv"
npzPath = "Npz"
provideXLSX = true
overwrite = false

[Video]
showEdgeDetection = true
showVideoFrames = true
playbackSpeed = "fast"

[Measurement]
roi = -1
rescaleFactor = 0.5
fromTime = -1
toTime = -1
pCRTAlgorithm = "best fit"
maxUncertaintyRatio = inf
initialGuesses = [1.0, -0.5, 0.0]

[ReleaseFrameDetection]
algorithm = "laplacian"
medianKernelRadius = 1

[ReleaseFrameDetection.canny]
thresh1 = 47
thresh2 = 64
blurKernel = 5
l2grad = true
cannyPlateau = 8.261879165862927
cannySmoothingKernel = 1
cannyGradientSmoothingKernel = 3
indexOffset = 2

[ReleaseFrameDetection.laplacian]
scale = 1
delta = 0
ksize = 3
blurKernel = 8
laplacianPlateau = 1.7953339084618558
laplacianSmoothingKernel = 17
laplacianGradientSmoothingKernel = 5
indexOffset = -2

[AverageIntensitySlicing]
strictMinGrad = -1.829632093303938
strictMaxGrad = 1.9570490981053659
relaxMinGrad = -9.36934937254803
relaxMaxGrad = 9.634807412781452
offsetTime = 0.10563336383996912

[General]
askConfirmation = true
showAllPlots = false
showBGRPlot = true
showLABPlot = true
showEdgeDetectionPlot = false
writeLogFile = true
logLevel = "DEBUG"
