[targets]
"0528_test1.1.mp4" = { crtIntervalStartIndex = 144, crtIntervalEndIndex = 294 }
"0528_test1.2.mp4" = { crtIntervalStartIndex = 138, crtIntervalEndIndex = 286 }
"0528_test1.4.mp4" = { crtIntervalStartIndex = 151, crtIntervalEndIndex = 299 }
"0528_test1.5.mp4" = { crtIntervalStartIndex = 143, crtIntervalEndIndex = 290 }
"0528_test3.6.mp4" = { crtIntervalStartIndex = 151, crtIntervalEndIndex = 301 }
"0528_test4.1.mp4" = { crtIntervalStartIndex = 152, crtIntervalEndIndex = 301 }
"0528_test4.2.mp4" = { crtIntervalStartIndex = 148, crtIntervalEndIndex = 298 }
"0528_test4.3.mp4" = { crtIntervalStartIndex = 149, crtIntervalEndIndex = 296 }
"0528_test4.4.mp4" = { crtIntervalStartIndex = 142, crtIntervalEndIndex = 289 }
"0528_test4.5.mp4" = { crtIntervalStartIndex = 172, crtIntervalEndIndex = 320 }
"0528_test4.6.mp4" = { crtIntervalStartIndex = 166, crtIntervalEndIndex = 314 }
"CRT1.mp4" = { crtIntervalStartIndex = 365, crtIntervalEndIndex = 527 }
"CRT2.mp4" = { crtIntervalStartIndex = 369, crtIntervalEndIndex = 474 }
"CRT3.mp4" = { crtIntervalStartIndex = 368, crtIntervalEndIndex = 473 }
"DSC_0069.MOV" = { crtIntervalStartIndex = 685, crtIntervalEndIndex = 1058 }
"0528_test1.3.mp4" = { crtIntervalStartIndex = 147, crtIntervalEndIndex = 295 }
"0528_test1.6.mp4" = { crtIntervalStartIndex = 151, crtIntervalEndIndex = 300 }
"0528_test2.1.mp4" = { crtIntervalStartIndex = 152, crtIntervalEndIndex = 300 }
"0528_test2.2.mp4" = { crtIntervalStartIndex = 149, crtIntervalEndIndex = 299 }
"0528_test2.3.mp4" = { crtIntervalStartIndex = 155, crtIntervalEndIndex = 304 }
"0528_test2.4.mp4" = { crtIntervalStartIndex = 184, crtIntervalEndIndex = 331 }
"0528_test2.5.mp4" = { crtIntervalStartIndex = 134, crtIntervalEndIndex = 283 }
"0528_test3.1.mp4" = { crtIntervalStartIndex = 152, crtIntervalEndIndex = 302 }
"0528_test3.2.mp4" = { crtIntervalStartIndex = 148, crtIntervalEndIndex = 299 }
"0528_test3.3.mp4" = { crtIntervalStartIndex = 151, crtIntervalEndIndex = 302 }
"0528_test3.4.mp4" = { crtIntervalStartIndex = 149, crtIntervalEndIndex = 302 }
"0528_test3.5.mp4" = { crtIntervalStartIndex = 129, crtIntervalEndIndex = 276 }
"experiment 1.wmv" = { crtIntervalStartIndex = 249, crtIntervalEndIndex = 487 }
"experiment 2.wmv" = { crtIntervalStartIndex = 195, crtIntervalEndIndex = 442 }
"experiment 3.mp4" = { crtIntervalStartIndex = 293, crtIntervalEndIndex = 524 }
"experiment 4.wmv" = { crtIntervalStartIndex = 362, crtIntervalEndIndex = 618 }
"P01CR1.wmv" = { crtIntervalStartIndex = 424, crtIntervalEndIndex = 856 }
"P01CR2.wmv" = { crtIntervalStartIndex = 390, crtIntervalEndIndex = 859 }
"P01CR3.wmv" = { crtIntervalStartIndex = 399, crtIntervalEndIndex = 848 }
"P01CR4.wmv" = { crtIntervalStartIndex = 391, crtIntervalEndIndex = 909 }
"P01CR5.wmv" = { crtIntervalStartIndex = 413, crtIntervalEndIndex = 855 }
"P02CR1.wmv" = { crtIntervalStartIndex = 415, crtIntervalEndIndex = 878 }
"P02CR4.wmv" = { crtIntervalStartIndex = 417, crtIntervalEndIndex = 879 }
"P02CR5.wmv" = { crtIntervalStartIndex = 461, crtIntervalEndIndex = 932 }
"P03CR1.wmv" = { crtIntervalStartIndex = 394, crtIntervalEndIndex = 862 }
"P03CR2.wmv" = { crtIntervalStartIndex = 394, crtIntervalEndIndex = 878 }
"P03CR3.wmv" = { crtIntervalStartIndex = 398, crtIntervalEndIndex = 854 }
"P03CR4.wmv" = { crtIntervalStartIndex = 414, crtIntervalEndIndex = 868 }
"P03CR5.wmv" = { crtIntervalStartIndex = 413, crtIntervalEndIndex = 862 }
"P04CR1.wmv" = { crtIntervalStartIndex = 382, crtIntervalEndIndex = 853 }
"P04CR2.wmv" = { crtIntervalStartIndex = 382, crtIntervalEndIndex = 845 }
"P04CR3.wmv" = { crtIntervalStartIndex = 387, crtIntervalEndIndex = 846 }
"P04CR4.wmv" = { crtIntervalStartIndex = 387, crtIntervalEndIndex = 851 }
"P04CR5.wmv" = { crtIntervalStartIndex = 384, crtIntervalEndIndex = 852 }
"P05CR1.wmv" = { crtIntervalStartIndex = 421, crtIntervalEndIndex = 862 }
"P05CR2.wmv" = { crtIntervalStartIndex = 410, crtIntervalEndIndex = 855 }
"P05CR3.wmv" = { crtIntervalStartIndex = 403, crtIntervalEndIndex = 858 }
"P05CR4.wmv" = { crtIntervalStartIndex = 394, crtIntervalEndIndex = 853 }
"P05CR5.wmv" = { crtIntervalStartIndex = 388, crtIntervalEndIndex = 880 }
"P06CR1.wmv" = { crtIntervalStartIndex = 410, crtIntervalEndIndex = 853 }
"P06CR2.wmv" = { crtIntervalStartIndex = 384, crtIntervalEndIndex = 855 }
"P06CR3.wmv" = { crtIntervalStartIndex = 399, crtIntervalEndIndex = 850 }
"P06CR4.wmv" = { crtIntervalStartIndex = 390, crtIntervalEndIndex = 853 }
"P06CR5.wmv" = { crtIntervalStartIndex = 399, crtIntervalEndIndex = 856 }
"P07CR1.wmv" = { crtIntervalStartIndex = 458, crtIntervalEndIndex = 882 }
"P07CR2.wmv" = { crtIntervalStartIndex = 413, crtIntervalEndIndex = 859 }
"P07CR3.wmv" = { crtIntervalStartIndex = 414, crtIntervalEndIndex = 871 }
"P07CR4.wmv" = { crtIntervalStartIndex = 405, crtIntervalEndIndex = 849 }
"P07CR5.wmv" = { crtIntervalStartIndex = 432, crtIntervalEndIndex = 887 }
"P08CR1.wmv" = { crtIntervalStartIndex = 417, crtIntervalEndIndex = 857 }
"P08CR2.wmv" = { crtIntervalStartIndex = 406, crtIntervalEndIndex = 853 }
"P08CR3.wmv" = { crtIntervalStartIndex = 412, crtIntervalEndIndex = 861 }
"P08CR4.wmv" = { crtIntervalStartIndex = 410, crtIntervalEndIndex = 868 }
"P08CR5.wmv" = { crtIntervalStartIndex = 412, crtIntervalEndIndex = 856 }
"P09CR1.wmv" = { crtIntervalStartIndex = 420, crtIntervalEndIndex = 859 }
"P09CR2.wmv" = { crtIntervalStartIndex = 408, crtIntervalEndIndex = 873 }
"P09CR3.wmv" = { crtIntervalStartIndex = 385, crtIntervalEndIndex = 858 }
"P09CR4.wmv" = { crtIntervalStartIndex = 398, crtIntervalEndIndex = 851 }
"P09CR5.wmv" = { crtIntervalStartIndex = 442, crtIntervalEndIndex = 865 }
"P10CR1.wmv" = { crtIntervalStartIndex = 418, crtIntervalEndIndex = 860 }
"P10CR2.wmv" = { crtIntervalStartIndex = 429, crtIntervalEndIndex = 856 }
"P10CR3.wmv" = { crtIntervalStartIndex = 409, crtIntervalEndIndex = 858 }
"P10CR4.wmv" = { crtIntervalStartIndex = 423, crtIntervalEndIndex = 857 }
"P10CR5.wmv" = { crtIntervalStartIndex = 415, crtIntervalEndIndex = 863 }
"P11CR1.wmv" = { crtIntervalStartIndex = 407, crtIntervalEndIndex = 859 }
"P11CR2.wmv" = { crtIntervalStartIndex = 401, crtIntervalEndIndex = 876 }
"P11CR3.wmv" = { crtIntervalStartIndex = 413, crtIntervalEndIndex = 867 }
"P11CR4.wmv" = { crtIntervalStartIndex = 405, crtIntervalEndIndex = 855 }
"P11CR5.wmv" = { crtIntervalStartIndex = 408, crtIntervalEndIndex = 841 }
"P12CR1.wmv" = { crtIntervalStartIndex = 399, crtIntervalEndIndex = 863 }
"P12CR2.wmv" = { crtIntervalStartIndex = 401, crtIntervalEndIndex = 859 }
"P12CR3.wmv" = { crtIntervalStartIndex = 414, crtIntervalEndIndex = 856 }
"P12CR4.wmv" = { crtIntervalStartIndex = 417, crtIntervalEndIndex = 854 }
"P12CR5.wmv" = { crtIntervalStartIndex = 409, crtIntervalEndIndex = 859 }
"P13CR1.wmv" = { crtIntervalStartIndex = 442, crtIntervalEndIndex = 861 }
"P13CR2.wmv" = { crtIntervalStartIndex = 406, crtIntervalEndIndex = 859 }
"P13CR3.wmv" = { crtIntervalStartIndex = 436, crtIntervalEndIndex = 863 }
"P13CR4.wmv" = { crtIntervalStartIndex = 413, crtIntervalEndIndex = 869 }
"P13CR5.wmv" = { crtIntervalStartIndex = 417, crtIntervalEndIndex = 860 }
"P14CR1.wmv" = { crtIntervalStartIndex = 409, crtIntervalEndIndex = 861 }
"P14CR2.wmv" = { crtIntervalStartIndex = 407, crtIntervalEndIndex = 850 }
"P14CR3.wmv" = { crtIntervalStartIndex = 406, crtIntervalEndIndex = 846 }
"P14CR4.wmv" = { crtIntervalStartIndex = 400, crtIntervalEndIndex = 857 }
"P14CR5.wmv" = { crtIntervalStartIndex = 411, crtIntervalEndIndex = 866 }
"P15CR1.wmv" = { crtIntervalStartIndex = 423, crtIntervalEndIndex = 857 }
"P15CR2.wmv" = { crtIntervalStartIndex = 457, crtIntervalEndIndex = 861 }
"P15CR3.wmv" = { crtIntervalStartIndex = 394, crtIntervalEndIndex = 878 }
"P15CR4.wmv" = { crtIntervalStartIndex = 417, crtIntervalEndIndex = 862 }
"P15CR5.wmv" = { crtIntervalStartIndex = 413, crtIntervalEndIndex = 880 }
"P16CR1.wmv" = { crtIntervalStartIndex = 406, crtIntervalEndIndex = 844 }
"P16CR2.wmv" = { crtIntervalStartIndex = 383, crtIntervalEndIndex = 855 }
"P16CR3.wmv" = { crtIntervalStartIndex = 390, crtIntervalEndIndex = 864 }
"P16CR4.wmv" = { crtIntervalStartIndex = 403, crtIntervalEndIndex = 850 }
"P16CR5.wmv" = { crtIntervalStartIndex = 432, crtIntervalEndIndex = 864 }
"P17CR1.wmv" = { crtIntervalStartIndex = 415, crtIntervalEndIndex = 855 }
"P17CR2.wmv" = { crtIntervalStartIndex = 390, crtIntervalEndIndex = 858 }
"P17CR3.wmv" = { crtIntervalStartIndex = 400, crtIntervalEndIndex = 846 }
"P17CR4.wmv" = { crtIntervalStartIndex = 399, crtIntervalEndIndex = 856 }
"P17CR5.wmv" = { crtIntervalStartIndex = 410, crtIntervalEndIndex = 857 }
"P18CR1.wmv" = { crtIntervalStartIndex = 414, crtIntervalEndIndex = 855 }
"P18CR2.wmv" = { crtIntervalStartIndex = 390, crtIntervalEndIndex = 858 }
"P18CR3.wmv" = { crtIntervalStartIndex = 399, crtIntervalEndIndex = 846 }
"P18CR4.wmv" = { crtIntervalStartIndex = 400, crtIntervalEndIndex = 855 }
"P18CR5.wmv" = { crtIntervalStartIndex = 411, crtIntervalEndIndex = 857 }
"P19CR1.wmv" = { crtIntervalStartIndex = 402, crtIntervalEndIndex = 855 }
"P19CR2.wmv" = { crtIntervalStartIndex = 395, crtIntervalEndIndex = 867 }
"P19CR3.wmv" = { crtIntervalStartIndex = 405, crtIntervalEndIndex = 852 }
"P19CR4.wmv" = { crtIntervalStartIndex = 409, crtIntervalEndIndex = 875 }
"P19CR5.wmv" = { crtIntervalStartIndex = 431, crtIntervalEndIndex = 921 }
"P20CR1.wmv" = { crtIntervalStartIndex = 379, crtIntervalEndIndex = 849 }
"P20CR2.wmv" = { crtIntervalStartIndex = 392, crtIntervalEndIndex = 864 }
"P20CR3.wmv" = { crtIntervalStartIndex = 397, crtIntervalEndIndex = 851 }
"P20CR4.wmv" = { crtIntervalStartIndex = 460, crtIntervalEndIndex = 895 }
"P20CR5.wmv" = { crtIntervalStartIndex = 419, crtIntervalEndIndex = 873 }
"P21CR1.wmv" = { crtIntervalStartIndex = 388, crtIntervalEndIndex = 850 }
"P21CR2.wmv" = { crtIntervalStartIndex = 398, crtIntervalEndIndex = 870 }
"P21CR3.wmv" = { crtIntervalStartIndex = 384, crtIntervalEndIndex = 844 }
"P21CR4.wmv" = { crtIntervalStartIndex = 431, crtIntervalEndIndex = 881 }
"P21CR5.wmv" = { crtIntervalStartIndex = 385, crtIntervalEndIndex = 859 }
"P22CR1.wmv" = { crtIntervalStartIndex = 384, crtIntervalEndIndex = 857 }
"P22CR2.wmv" = { crtIntervalStartIndex = 392, crtIntervalEndIndex = 855 }
"P22CR3.wmv" = { crtIntervalStartIndex = 393, crtIntervalEndIndex = 849 }
"P22CR4.wmv" = { crtIntervalStartIndex = 406, crtIntervalEndIndex = 882 }
"P22CR5.wmv" = { crtIntervalStartIndex = 388, crtIntervalEndIndex = 861 }
"P23CR1.wmv" = { crtIntervalStartIndex = 502, crtIntervalEndIndex = 873 }
"P23CR2.wmv" = { crtIntervalStartIndex = 394, crtIntervalEndIndex = 841 }
"P23CR3.wmv" = { crtIntervalStartIndex = 441, crtIntervalEndIndex = 857 }
"P23CR4.wmv" = { crtIntervalStartIndex = 435, crtIntervalEndIndex = 877 }
"P23CR5.wmv" = { crtIntervalStartIndex = 410, crtIntervalEndIndex = 876 }
"P24CR1.wmv" = { crtIntervalStartIndex = 462, crtIntervalEndIndex = 861 }
"P24CR2.wmv" = { crtIntervalStartIndex = 421, crtIntervalEndIndex = 855 }
"P24CR3.wmv" = { crtIntervalStartIndex = 447, crtIntervalEndIndex = 862 }
"P24CR4.wmv" = { crtIntervalStartIndex = 449, crtIntervalEndIndex = 865 }
"P24CR5.wmv" = { crtIntervalStartIndex = 416, crtIntervalEndIndex = 863 }
"P25CR1.wmv" = { crtIntervalStartIndex = 415, crtIntervalEndIndex = 859 }
"P25CR2.wmv" = { crtIntervalStartIndex = 409, crtIntervalEndIndex = 837 }
"P25CR3.wmv" = { crtIntervalStartIndex = 480, crtIntervalEndIndex = 860 }
"P25CR4.wmv" = { crtIntervalStartIndex = 445, crtIntervalEndIndex = 853 }
"P25CR5.wmv" = { crtIntervalStartIndex = 445, crtIntervalEndIndex = 840 }
"P26CR1.wmv" = { crtIntervalStartIndex = 463, crtIntervalEndIndex = 861 }
"P26CR2.wmv" = { crtIntervalStartIndex = 422, crtIntervalEndIndex = 855 }
"P26CR3.wmv" = { crtIntervalStartIndex = 445, crtIntervalEndIndex = 862 }
"P26CR4.wmv" = { crtIntervalStartIndex = 446, crtIntervalEndIndex = 865 }
"P26CR5.wmv" = { crtIntervalStartIndex = 414, crtIntervalEndIndex = 863 }
"P27CR1.wmv" = { crtIntervalStartIndex = 400, crtIntervalEndIndex = 858 }
"P27CR2.wmv" = { crtIntervalStartIndex = 399, crtIntervalEndIndex = 858 }
"P27CR3.wmv" = { crtIntervalStartIndex = 453, crtIntervalEndIndex = 852 }
"P27CR4.wmv" = { crtIntervalStartIndex = 432, crtIntervalEndIndex = 859 }
"P27CR5.wmv" = { crtIntervalStartIndex = 406, crtIntervalEndIndex = 861 }
"P28CR1.wmv" = { crtIntervalStartIndex = 429, crtIntervalEndIndex = 855 }
"P28CR2.wmv" = { crtIntervalStartIndex = 405, crtIntervalEndIndex = 901 }
"P28CR3.wmv" = { crtIntervalStartIndex = 374, crtIntervalEndIndex = 862 }
"P28CR4.wmv" = { crtIntervalStartIndex = 415, crtIntervalEndIndex = 857 }
"P28CR5.wmv" = { crtIntervalStartIndex = 375, crtIntervalEndIndex = 864 }
"P29CR1.wmv" = { crtIntervalStartIndex = 538, crtIntervalEndIndex = 873 }
"P29CR2.wmv" = { crtIntervalStartIndex = 421, crtIntervalEndIndex = 859 }
"P29CR3.wmv" = { crtIntervalStartIndex = 401, crtIntervalEndIndex = 860 }
"P29CR4.wmv" = { crtIntervalStartIndex = 401, crtIntervalEndIndex = 860 }
"P29CR5.wmv" = { crtIntervalStartIndex = 402, crtIntervalEndIndex = 867 }
"P30CR1.wmv" = { crtIntervalStartIndex = 400, crtIntervalEndIndex = 857 }
"P30CR2.wmv" = { crtIntervalStartIndex = 416, crtIntervalEndIndex = 853 }
"P30CR3.wmv" = { crtIntervalStartIndex = 421, crtIntervalEndIndex = 851 }
"P30CR4.wmv" = { crtIntervalStartIndex = 421, crtIntervalEndIndex = 855 }
"P30CR5.wmv" = { crtIntervalStartIndex = 421, crtIntervalEndIndex = 860 }
"P31CR1.wmv" = { crtIntervalStartIndex = 401, crtIntervalEndIndex = 882 }
"P31CR2.wmv" = { crtIntervalStartIndex = 413, crtIntervalEndIndex = 867 }
"P31CR3.wmv" = { crtIntervalStartIndex = 408, crtIntervalEndIndex = 868 }
"P31CR4.wmv" = { crtIntervalStartIndex = 398, crtIntervalEndIndex = 864 }
"P31CR5.wmv" = { crtIntervalStartIndex = 404, crtIntervalEndIndex = 861 }
"v1.mp4" = { crtIntervalStartIndex = 289, crtIntervalEndIndex = 434 }
"Video 142.mp4" = { crtIntervalStartIndex = 282, crtIntervalEndIndex = 517 }
"Video 145.mp4" = { crtIntervalStartIndex = 312, crtIntervalEndIndex = 546 }
"Video 148.mp4" = { crtIntervalStartIndex = 261, crtIntervalEndIndex = 494 }
"Video 151.mp4" = { crtIntervalStartIndex = 289, crtIntervalEndIndex = 461 }
"Video 154.mp4" = { crtIntervalStartIndex = 257, crtIntervalEndIndex = 485 }
"Video 157.mp4" = { crtIntervalStartIndex = 290, crtIntervalEndIndex = 504 }
"video.mp4" = { crtIntervalStartIndex = 468, crtIntervalEndIndex = 623 }
